# Generated by Django 5.2.10 on 2026-02-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_resumeexperience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeexperience',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
