# Generated by Django 5.2.10 on 2026-02-08 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_resumeeducation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumeeducation',
            old_name='feld_of_study',
            new_name='field_of_study',
        ),
    ]
