# Generated by Django 6.0.2 on 2026-03-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0010_resumetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeheader',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
