# Generated by Django 5.2.10 on 2026-03-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0011_resumeheader_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeeducation',
            name='end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resumeeducation',
            name='start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resumeexperience',
            name='start_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resumeexperience',
            name='start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
