# Generated by Django 5.2.4 on 2026-03-31 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0013_resumelanguage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumelanguage',
            name='language_name',
        ),
        migrations.AddField(
            model_name='resumelanguage',
            name='language',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
